<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/06 05:56:50
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_app_max_jobs_on_category' => 10,
  'app_sf_upload_dir' => '/uploads/jobs/',
));
