<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/11/29 09:35:28
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
    'credentials' => 'show',
  ),
  'showcategory' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
  ),
);
