<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/29 10:25:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
